/* generated by src/portals/index.gen.ts */
import {type PortalsData, type PortalData} from './portal';

import HomePortalData from './home/data';
import AboutPortalData from './about/data';
import DeepBreathPortalData from './deep-breath/data';
import StarlitHammockPortalData from './starlit-hammock/data';
import Easings2PortalData from './easings-2/data';
import PaintFreqsPortalData from './paint-freqs/data';
import Easings1PortalData from './easings-1/data';
import HearingTestPortalData from './hearing-test/data';
import UnderConstructionPortalData from './under-construction/data';
import FreqSpeedsPortalData from './freq-speeds/data';
import TransitionDesignerPortalData from './transition-designer/data';
import ClocksPortalData from './clocks/data';
import FreqSpectaclePortalData from './freq-spectacle/data';
import VoidPortalData from './void/data';

const portals: PortalData[] = [
	HomePortalData,
	AboutPortalData,
	DeepBreathPortalData,
	StarlitHammockPortalData,
	Easings2PortalData,
	PaintFreqsPortalData,
	Easings1PortalData,
	HearingTestPortalData,
	UnderConstructionPortalData,
	FreqSpeedsPortalData,
	TransitionDesignerPortalData,
	ClocksPortalData,
	FreqSpectaclePortalData,
	VoidPortalData,
];

export const portalsData: PortalsData = {
	portals,
	portalsBySlug: new Map(portals.map((p) => [p.slug, p])),
};
